routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\MenteeController;
use App\Http\Controllers\Mentor\MentorController;
use App\Http\Controllers\Admin\DashboardController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::middleware(['auth'])->group(function () {
    Route::get('/home', [HomeController::class, 'index'])->name('home');
});

Route::post('authenticate', [LoginController::class, 'authenticate'])->name('authenticate');

// Admin Routes
//
Route::middleware(['auth', 'auth.isAdmin'])->prefix('admin')->name('admin.')->group(function () {
    Route::resource('/users', UserController::class);
    Route::resource('/mentees', MenteeController::class);
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
    Route::patch('/approve-mentee/{mentee_id}', [MenteeController::class, 'approve'])->name('mentee.approve');

});

// Mentor/Teacher Routes
Route::middleware(['auth', 'auth.isMentor'])->prefix('teacher')->name('teacher.')->group(function () {
    Route::resource('/users', MentorController::class);
    Route::get('/dashboard', [MentorController::class, 'index'])->name('dashboard');
});

app/Models/Mentee.php
<?php

namespace App\Models;

use App\Models\Mentor;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Mentee extends Model
{
    use HasFactory;

    protected $fillable = [
        'first_name',
        'last_name',
        'user_id',
        'mentor_id',
        'payment_status',
        'amount_paid',
        'approval_status'
    ];

    public function mentor()
    {
        return $this->belongsTo(Mentor::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

}

app/Http/Controllers/Admin/MenteeController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Role;
use App\Models\Mentee;
use App\Models\Mentor;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Actions\Fortify\CreateNewUser;
use App\Http\Requests\Admin\MenteeRequest;

class MenteeController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth', 'auth.isAdmin']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $mentees = Mentee::paginate(10);
        // dd($users);

        return view('admin.mentees.index')->with(
            [
                'users' => $mentees
            ]
        );
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.mentees.create', [
            'roles' => Role::all(),
            'mentors' => Mentor::all(),
            'mentees' => Mentee::all()
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(MenteeRequest $request)
    {
        $role = '4';

        $newUser = new CreateNewUser();

        $user = $newUser->create(array_merge($request->only('first-name', 'last-name', 'email', 'password', 'password_confirmation'), ['msisdn' => null]));

        $mentee = Mentee::create([
            'first_name' => $user->first_name,
            'last_name' => $user->last_name,
            'user_id' => $user->id,
            'mentor_id' => $request['mentor']
        ]);


        $user->roles()->sync($request->roles);

        session()->flash('success', 'Mentee Created Successfully!');

        return redirect(route('admin.mentees.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    /**
     * Approve mentee to access resources post payment.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function approve($id)
    {
        $mentee = Mentee::findorFail($id);

        if ($mentee->amount_paid < 45000.00) {
            session()->flash('failure', 'Approval Failed! Invalid Payment.');
            return redirect()->back();
        }
        $mentee->update(['approval_status' => true]);
        $mentee->save();

        return redirect(route('admin.mentees.index'));
    }
}

app/Http/Controllers/Mentee/MenteeController.php
<?php

namespace App\Http\Controllers\Mentee;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class MenteeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/mentees/create.blade.php
@extends('admin.templates.main')
@section('header')
Mentee Management
@endsection

@section('css')

<!-- MULTI SELECT TOOL -SELECT2 -->
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />
@endsection

@section('content')
<h2>Add Mentee</h2>
<div class="card authform">
    <div class="card-body">
        @include('partials.alerts')
        <form method="POST" action="{{ route('admin.mentees.store') }}" class="m-4">
            @include('admin.mentees.partials.form')
        </form>
    </div>
</div>
@endsection

@section('scripts')
<!-- MULTI SELECT TOOL -SELECT2 -->
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>

<script>
    $(document).ready(() => {
        // $(".roles-selector").select2({
        //     tags: true
        // });

        // $('#role4').click(function() {
        //     console.log('a');
        //     if ($("#roles option[value=4]:selected").length > 0) {
        //         console.log('b');

        //         $('#mentorSection').attr('hidden', false);

        //     } else {

        //         $('#mentorSection').attr('hidden', true);

        //     }
        // });

        // $('#roles').on('change', function() {
        //     let selectObject = $('#roles').select2('data');

        //     let found = false;

        //     if (selectObject === undefined || selectObject.length == 0) {
        //         $('#mentorSection').attr('hidden', true);
        //     }

        //     for (var i = 0; i < selectObject.length; i++) {
        //         if (selectObject[i].text == 'Student') {
        //             found = true;
        //             $('#mentorSection').attr('hidden', false);
        //             break;
        //         } else {
        //             $('#mentorSection').attr('hidden', true);
        //         }
        //     }


        // });
        let val = $("#roles").val();

        if (val == '4') {
            $('#mentorSection').attr('hidden', false);
        } else {
            $('#mentorSection').attr('hidden', true);
        }

        $("#roles").change(function() {
            var val = $(this).val();

            if (val == '4') {
                $('#mentorSection').attr('hidden', false);
            } else {
                $('#mentorSection').attr('hidden', true);
            }

        });
    });
</script>
@endsection

resources/views/admin/mentees/edit.blade.php
@extends('admin.templates.main')
@section('header')
Edit User
@endsection

@section('css')

<!-- MULTI SELECT TOOL -SELECT2 -->
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />
@endsection

@section('content')
<h1>Edit User</h1>
<div class="card authform">
    <div class="card-body">
        @include('partials.alerts')
        <form method="POST" action="{{ route('admin.users.update', $user->id) }} class=" m-4"">
            @method('PATCH')
            @include('admin.users.partials.form')
        </form>
    </div>
</div>
@endsection

@section('scripts')
<!-- MULTI SELECT TOOL -SELECT2 -->
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>

<script>
    $(document).ready(() => {
        // $(".roles-selector").select2({
        //     tags: true
        // });

        // let selectObject = $('#roles').select2('data');

        // let found = false;

        // if (selectObject === undefined || selectObject.length == 0) {
        //     $('#mentorSection').attr('hidden', true);
        // }

        // for (var i = 0; i < selectObject.length; i++) {
        //     if (selectObject[i].text == 'Student') {
        //         found = true;
        //         $('#mentorSection').attr('hidden', false);
        //         break;
        //     } else {
        //         $('#mentorSection').attr('hidden', true);
        //     }
        // }

        // $('#roles').on('change', function() {
        //     let selectObject = $('#roles').select2('data');

        //     let found = false;

        //     if (selectObject === undefined || selectObject.length == 0) {
        //         $('#mentorSection').attr('hidden', true);
        //     }

        //     for (var i = 0; i < selectObject.length; i++) {
        //         if (selectObject[i].text == 'Student') {
        //             found = true;
        //             $('#mentorSection').attr('hidden', false);
        //             break;
        //         } else {
        //             $('#mentorSection').attr('hidden', true);
        //         }
        //     }

        // });

        let val = $("#roles").val();

        if (val == '4') {
            console.log('yes');
            $('#mentorSection').attr('hidden', false);
        } else {
            $('#mentorSection').attr('hidden', true);
        }

        $("#roles").change((function() {
            var val = $(this).val();

            if (val == '4') {
                console.log('yes C');

                $('#mentorSection').attr('hidden', false);
            } else {
                $('#mentorSection').attr('hidden', true);
            }

        }));

    })
</script>
@endsection

resources/views/admin/mentees/index.blade.php
@extends('admin.templates.main')

@section('header')
Mentee Management
@endsection

@section('content')

<div class="row">
    <div class="col-12">
        <h1 class="float-left"></h1>
        <a href="{{ route('admin.mentees.create') }}" class="btn btn-sm btn-success float-right" role="button">Add Mentee</a>

    </div>
</div>
@include('partials.alerts')
<div class="row">
    <div class="col-lg-12 col-md-12">
        <div class="card">
            <div class="card-header card-header-primary">
                <h4 class="card-title">Mentees</h4>
                <p class="card-category">View and Approve Mentees</p>
            </div>
            <div class="card-body table-responsive">
                <table class="table table-hover w-auto">
                    <thead class="text-primary">
                        <tr>
                            <th scope="col">ID</th>
                            <th scope="col">First Name</th>
                            <th scope="col">Last Name</th>
                            <th scope="col">MSISDN</th>
                            <th scope="col" class="text-center">Email</th>
                            <th scope="col" class="text-center">Payment Status</th>
                            <th scope="col" class="text-center">Approval Status</th>
                            <th scope="col" class="text-center">Actions</th>

                        </tr>
                    </thead>
                    <tbody>
                        @foreach($users as $user)
                        <tr>
                            <th scope="row">{{ $user->id }}</th>
                            <td>{{ $user->first_name }}</td>
                            <td>{{ $user->last_name }}</td>
                            <td>{{ $user->msisdn }}</td>
                            <td class="text-center">{{ $user->email }}</td>
                            <td class="text-center">{{ $user->payment_status }}</td>
                            <td class="text-center">
                                @if($user->approval_status)
                                Approved
                                @else
                                Not approved
                                <form action="{{ route('admin.mentee.approve', $user->id) }}" method="POST" id="deleteUserForm{{ $user->id }}" class="align-self-center mx-1" style="display: inline;">
                                    @csrf
                                    @method('PATCH')

                                    <button type="submit" class="btn btn-success btn-sm align-self-end"><i class="material-icons">check_box</i> Approve</button>
                                </form>
                                @endif
                            </td>
                            <td class="text-center">
                                <a href="{{ route('admin.mentees.edit', $user->id) }}" class="btn btn-sm btn-warning align-self-center mx-auto" role="button"><i class="material-icons">edit</i> Edit</a>
                            </td>

                        </tr>
                        @endforeach
                    </tbody>
                </table>
                {{ $users->links() }}

            </div>
        </div>

    </div>
</div>
@endsection

resources/views/admin/mentees/show.blade.php
@extends('admin.templates.main')

@section('header')
User Management
@endsection

@section('content')
{{--dd($mentor)--}}

<h3 class="display-4 mt-0" style="color: teal;">User Information</h3>
<hr>
<br>
<div class=" h-100 d-flex justify-content-center align-items-center">
    <div class="col-md-6 m-6">
        <div class="card card-profile">
            <div class="card-avatar">
                <a href="javascript:;">
                    <img class="img" src="../assets/img/faces/marc.jpg" />
                </a>
            </div>
            <div class="card-body p-4">
            <h4 class="card-title mt-5">{{ $user->first_name }} {{ $user->last_name }}</h4>

                <h6 class="card-category text-gray">{{ $user->first_name }} Role</h4>
                    <p class="card-description">
                </h6>

                <p class="card-description mt-2"><span>Email: </span>{{ $user->email }}</h4>
                <p class="card-description mt-2"><span>Phone Number: </span>{{ $user->msisdn }}</h4>

                            @if($user->isMentee($user->id))
                <p class="card-description"><span>Mentor: </span>{{ $mentor->first_name }} {{ $mentor->last_name }}</h4>
                    @elseif($user->isMentor($user->id))
                <p class="card-description"><span>Mentees: </span></h4>
                    @if(isset($mentees))
                <ul>
                    @foreach($mentees as $mentee)
                    <li>{{ $mentee->first_name }} {{ $mentee->last_name }}</li>
                    @endforeach
                </ul>
                @else
                <p class="card-description">No mentee assigned to user</h4>
                    @endif
                    @endif
                <div class="row">
                    <div class="col-md-6 text-center mx-auto mt-3 mb-2">
                        <a href="{{ route('admin.users.edit', $user->id) }}" class="btn btn-info btn-round mx-2">Edit</a>
                        <form action="{{ route('admin.users.destroy', $user->id) }}" method="POST" id="deleteUserForm{{ $user->id }}" class="mx-2" style="display: inline;">
                            @csrf
                            @method('DELETE')

                            <button type="submit" class="btn btn-danger btn-round">Delete</button>
                        </form>

                    </div>

                </div>

            </div>
        </div>
    </div>
</div>
@endsection